### ISSUE TITLE
Windows Security report Trojan let's fix

### ISSUE THREAD

**Issue by ghost** [FireMuffin303/What-it-should-be#1]
จากการตรวจสอบโค้ดเบื้องต้น ผมพบว่า mod มีการใช้งานฟีเจอร์หลายอย่างที่อาจทำให้ Windows เข้าใจผิดว่าเป็น trojan ซึ่งทางผมไม่ค่อยมีความรู้เรื่องทำ mod มาก ถ้าผิดตรงไหนต้องขออภัยด้วยนะครับ 
มีการเข้าถึงไฟล์ระบบเพื่อจัดการไฟล์ config
ใช้ File และ FileReader ใน src/main/java/net/firemuffin303/wisb/config/ModConfig.java
โค้ดที่น่าจะเป็น "file = new File(FabricLoader.getInstance().getConfigDir().toFile(),"wisb.json");" หรือ ตรงบรรทัดที่ 69
มีการใช้ ServerPlayNetworking เพื่อส่งข้อมูลระหว่าง server และ client ใน src/main/java/net/firemuffin303/wisb/Wisb.java
ซื่งคล้ายกับการทำงานของ Trojan ครับ เท่าที่ผมรู้เกี่ยวกับ trojan
ตำแหน่งโค้ดที่น่าจะเป็น บรรทัดที่ 58
ซื่งทั้งหมดนี้อาจทำให้ Windows สงสัยก็ได้ครับ
 ลองลดการใช้งาน File I/O ดูก่อนครับ
เรียกใช้ เฉพาะช่วงที่จำเป็น เพราะการทำให้มันเขียน/อ่านไฟล์ บ่อยๆ นี่จะตัวปัญหาเลยครับ ลองใช้ Fabric Config API ในการจัดการไฟล์แทนครับ และ faction บางอย่าง ลองใช้ API ของ Mod lib ทั้งหลายดูครับ ให้ mod ประเภท lib มันจัดการให้ครับ

**Comment by KrisanaponMeksamoot** [comment]
### คือผมไม่เจอไวรัสครับ
https://www.virustotal.com/gui/file/5cdaed75f6f16b18eefad2fe5efee3ffba44015271ef94dd02a8bb3606b49ce9
![image](https://github.com/user-attachments/assets/57995965-a23d-45fb-85ef-bac786c6dd5d)
![image](https://github.com/user-attachments/assets/c6d8b275-32e5-47a7-9d27-330509317fd0)
จาก[การสแกน source code](https://www.virustotal.com/gui/file/b9a48a529059c1f3bfd31df0ccf069e353f4e9a4011fa219798343ee8bd1041a/detection) ก็ไม่เจอครับ
(build โดยใช้ Gradle บน Linux)

### [บรรทัดที่ 69 ModConfig.java](https://github.com/FireMuffin303/What-it-should-be/blob/master/src/main/java/net/firemuffin303/wisb/config/ModConfig.java#L69) 
`file = new File(FabricLoader.getInstance().getConfigDir().toFile(),"wisb.json");`
การเขียนรูปแบบนี้ผมและโปรแกรมเมอร์คนอื่นทำประจำครับ
ไม่มีทางที่จะไปแก้ไขไฟล์ระบบได้เว้นแต่จะตั้งไห้ config folder อยู่ใน directory ของระบบ

### [บรรทัดที่ 58 Wisb.java](https://github.com/FireMuffin303/What-it-should-be/blob/master/src/main/java/net/firemuffin303/wisb/Wisb.java#L58)
`ServerPlayNetworking.registerGlobalReceiver(WISB_RENAME_NAMETAG,(renameNameTagPacket, serverPlayerEntity, packetSender) -> {`
ผมไม่คิดว่าจะมีปัญหาอะไรครับ
*ผมไม่แน่ใจว่าจะต้องตรวจสอบว่ามี exp พอหรือเปล่าตรง[บรรทัดที่ 71](https://github.com/FireMuffin303/What-it-should-be/blob/master/src/main/java/net/firemuffin303/wisb/Wisb.java#L71) ครับ

### การคาดเดา
ถ้า mod ไม่ได้อยู่ในแหล่งที่มาที่น่าเชื่อถือ เช่น Curseforge หรือ Modrinth ก็จะถูกมองว่าเป็นไวรัสได้ง่ายทั้งๆที่ไม่ใช่ครับ

**Comment by ghost** [comment]
นั้นสินะ แต่เมือ build แล้วส่งให้คนอื่น แล้วwindows มันฟ้องว่าเป็น Trojan ทางผมก็งงเหมือนกัน ทั้งๆที่ทุกอย่างในโค้ดก็ปกติ
ก็หน้าจะเป็นอย่างนั้นจริงๆนั้นแหละครับ เพราะทางเจ้าของมอดส่งมอดให้เพื่อนของเขา แล้วมันเป็น

**Comment by ghost** [comment]
ยังไงก็ขอบคุณเลยนะครับ ที่มาขยายความมากกว่านี้ ทางผมก็สงสัย

**Comment by FireMuffin303** [comment]
Addressing The Trojan Situation for anyone who just check in here | อธิบายเหตุการณ์ Trojan สำหรับคนที่เพิ่งเข้ามาเจอ
https://github.com/FireMuffin303/What-it-should-be/blob/master/TrojanIncident.md
